[package]
name = "yoink-cds"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
dotenvy = "0.15"
image = "0.25"
urlencoding = "2.1.3"